export const categories = [
  {
    name: "Trending Tools",
    slug: "trending-tools",
    icon: "🎲",
    description: "Popular tools currently trending among users.",
    tools: [
      {
        name: "QR Code Generator",
        slug: "qr-code-generator",
        icon: "🔳",
        description: "Generate QR codes for URLs, text, and more.",
      },
      {
        name: "Random Password Generator",
        slug: "random-password-generator",
        icon: "🔑",
        description: "Create strong, random passwords instantly.",
      },
      {
        name: "Random Name Generator",
        slug: "random-name-generator",
        icon: "🧑‍🤝‍🧑",
        description: "Generate random names for any purpose.",
      },
      {
        name: "Last Name Generator",
        slug: "last-name-generator",
        icon: "👤",
        description: "Generate random last names quickly.",
      },

      {
        name: "Random Username Generator",
        slug: "random-username-generator",
        icon: "👤",
        description: "Create unique usernames for online accounts.",
      },
      {
        name: "Random Choice Picker",
        slug: "random-choice-picker",
        icon: "🎲",
        description: "Pick a random choice from a list of options.",
      },
      {
        name: "Random Number Generator",
        slug: "random-number-generator",
        icon: "🎲",
        description: "Generate random numbers within a range.",
      },
      {
        name: "Lorem Ipsum Generator",
        slug: "lorem-ipsum-generator",
        icon: "📜",
        description: "Generate placeholder Lorem Ipsum text.",
      },
    ],
  },
  {
    name: "Ai Generators",
    slug: "ai-generators",
    icon: "🤖",
    description: "AI-powered generators for text, replies, and more.",
    tools: [
      {
        name: "AI Reply Generator",
        slug: "ai-reply-generator",
        icon: "💬",
        description: "Generate smart replies using AI.",
      },
      {
        name: "Ai Prompt Generator",
        slug: "ai-prompt-generator",
        icon: "🧠",
        description: "Create prompts for AI models.",
      },
      {
        name: "AI Prompt Optimizer",
        slug: "ai-prompt-optimizer",
        icon: "⚙️",
        description: "Optimize prompts for better AI results.",
      },
      {
        name: "AI Faq Generator",
        slug: "ai-faq-generator",
        icon: "❓",
        description: "Generate FAQ sections using AI.",
      },
      {
        name: "AI Answer Generator",
        slug: "ai-answer-generator",
        icon: "🅰️",
        description: "Generate answers to questions using AI.",
      },
      {
        name: "AI Email Response Generator",
        slug: "ai-email-response-generator",
        icon: "📧",
        description: "Generate email responses with AI assistance.",
      },
      {
        name: "Ai Letter Generator",
        slug: "ai-letter-generator",
        icon: "✉️",
        description: "Create letters using AI.",
      },
      {
        name: "AI Blog title Generator",
        slug: "ai-blog-title-generator",
        icon: "📝",
        description: "Generate catchy blog titles with AI.",
      },
      {
        name: "AI Saas Name Generator",
        slug: "ai-saas-name-generator",
        icon: "💡",
        description: "Generate SaaS product names using AI.",
      },
    ],
  },
  {
    name: "Generators",
    slug: "generators",
    icon: "⚙️",
    description: "Various generators for IDs, data, and changelogs.",
    tools: [
      {
        name: "UUID Generator",
        slug: "uuid-generator",
        icon: "🎲",
        description: "Generate universally unique identifiers (UUIDs).",
      },
      {
        name: "NanoID Generator",
        slug: "nanoid-generator",
        icon: "🧬",
        description: "Generate NanoIDs for compact unique IDs.",
      },
      {
        name: "Fake Data Generator",
        slug: "fake-data-generator",
        icon: "🧪",
        description: "Create fake data for testing and development.",
      },
      {
        name: "Changelog Generator",
        slug: "changelog-generator",
        icon: "📑",
        description: "Generate changelogs for your projects.",
      },
    ],
  },
  // {
  //   name: "Finance Calculators",
  //   slug: "finance-calculators",
  //   icon: "💵",
  //   tools: [
  //     { name: "Mortgage Calculator", slug: "mortgage-calculator", icon: "🏠" },
  //     {
  //       name: "Retirement Calculator",
  //       slug: "retirement-calculator",
  //       icon: "🏖️",
  //     },
  //     { name: "Savings Calculator", slug: "savings-calculator", icon: "💰" },
  //   ],
  // },
  // {
  //   name: "Business & Finance",
  //   slug: "business-finance",
  //   icon: "💼",
  //   tools: [
  //     { name: "Invoice Generator", slug: "invoice-generator", icon: "🧾" },
  //     {
  //       name: "Business Name Generator",
  //       slug: "business-name-generator",
  //       icon: "🏢",
  //     },
  //     { name: "SWOT Analysis Generator", slug: "swot-generator", icon: "📊" },
  // { name: "Pitch Deck Generator", slug: "pitch-deck-generator", icon: "📈" },
  // {
  //   name: "Business Idea Generator",
  //   slug: "business-idea-generator",
  //   icon: "💡",
  // },
  // { name: "Pdf to Faq Generator", slug: "pdf-to-faq-generator", icon: "📄❓" },
  // {
  //   name: "Webpage to Faq Generator",
  //   slug: "webpage-to-faq-generator",
  //   icon: "🌐❓",
  // },
  //   ],
  // },
  // {
  //   name: "Health & Fitness",
  //   slug: "health-fitness",
  //   icon: "💪",
  //   tools: [
  //     { name: "BMI Calculator", slug: "bmi-calculator", icon: "⚖️" },
  //     { name: "Calorie Tracker", slug: "calorie-tracker", icon: "🍎" },
  //     { name: "Water Intake Calculator", slug: "water-intake", icon: "💧" },
  //   ],
  // },
  // {
  //   name: "Writing & Content Creation",
  //   slug: "writing-content-creation",
  //   icon: "✍️",
  //   tools: [
  //     { name: "Grammar Checker", slug: "grammar-checker", icon: "📝" },
  //     { name: "Plagiarism Detector", slug: "plagiarism-detector", icon: "🔍" },
  //     { name: "Language Translator", slug: "language-translator", icon: "🌐" },
  //   ],
  // },
  // {
  //   name: "Productivity & Utilities",
  //   slug: "productivity-utilities",
  //   icon: "⚙️",
  //   tools: [
  //     { name: "Text Expander", slug: "text-expander", icon: "✍️" },
  //     { name: "Task Manager", slug: "task-manager", icon: "✅" },
  //     { name: "Pomodoro Timer", slug: "pomodoro-timer", icon: "⏲️" },
  //     { name: "Note Taker", slug: "note-taker", icon: "🗒️" },
  //   ],
  // },
  // {
  //   name: "Mindfulness & Relaxation",
  //   slug: "mindfulness-relaxation",
  //   icon: "🧘‍♂️",
  //   tools: [
  //     { name: "Breathing Exercise", slug: "breathing-exercise", icon: "🌬️" },
  //     { name: "Guided Meditation", slug: "guided-meditation", icon: "🧘‍♀️" },
  //     { name: "Sleep Sounds", slug: "sleep-sounds", icon: "😴" },
  //   ],
  // },
  // {
  //   name: "Text Analysis & Manipulation",
  //   slug: "text-analysis-manipulation",
  //   icon: "📝",
  //   tools: [
  //     { name: "Sentiment Analyzer", slug: "sentiment-analyzer", icon: "😊" },
  //     { name: "Readability Checker", slug: "readability-checker", icon: "📖" },
  //     { name: "Keyword Extractor", slug: "keyword-extractor", icon: "🔑" },
  //   ],
  // },
  // {
  //   name: "Code & Development",
  //   slug: "code-development",
  //   icon: "💻",
  //   tools: [
  //     { name: "Code Beautifier", slug: "code-beautifier", icon: "🧼" },
  //     { name: "Minify JavaScript", slug: "minify-javascript", icon: "🗜️" },
  //     { name: "HTML Formatter", slug: "html-formatter", icon: "🌐" },
  //     { name: "CSS Formatter", slug: "css-formatter", icon: "🎨" },
  //   ],
  // },
  // {
  //   name: "File and Data Conversion",
  //   slug: "file-data-conversion",
  //   icon: "🔄",
  //   tools: [
  //     { name: "Text to PDF Converter", slug: "text-to-pdf", icon: "📄" },
  //     { name: "PDF to Text Converter", slug: "pdf-to-text", icon: "📄" },
  //     { name: "Image to PDF Converter", slug: "image-to-pdf", icon: "🖼️" },
  //   ],
  // },
  {
    name: "Website & SEO",
    slug: "website-seo",
    icon: "🌐",
    description: "Tools for website optimization and SEO tasks.",
    tools: [
      {
        name: "Meta Tag Generator",
        slug: "meta-tag-generator",
        icon: "🏷️",
        description: "Generate meta tags for your website.",
      },
      {
        name: "Sitemap Finder and Checker",
        slug: "sitemap-finder-checker",
        icon: "🗺️",
        description: "Find and check sitemaps for websites.",
      },
      {
        name: "Sitemap Generator",
        slug: "sitemap-generator",
        icon: "🗺️",
        description: "Generate sitemaps for your website.",
      },
      {
        name: "XML Sitemap Generator",
        slug: "xml-sitemap-generator",
        icon: "🗺️",
        description: "Create XML sitemaps for SEO.",
      },
      {
        name: "Sitemap Validator",
        slug: "sitemap-validator",
        icon: "✅",
        description: "Validate your website's sitemap files.",
      },
      {
        name: "robots.txt Generator",
        slug: "robots-txt-generator",
        icon: "🤖",
        description: "Generate robots.txt files for web crawlers.",
      },
      {
        name: "OpenAPI Stub Generator",
        slug: "openapi-stub-generator",
        icon: "📘",
        description: "Generate OpenAPI stubs for APIs.",
      },
      {
        name: "README Generator",
        slug: "readme-generator",
        icon: "📖",
        description: "Create README files for your projects.",
      },
      {
        name: "Ads.txt Generator",
        slug: "ads-txt-generator",
        icon: "📄",
        description: "Generate ads.txt files for ad monetization.",
      },
    ],
  },
  {
    name: "Data Conversion & Formatting",
    slug: "data-convertor",
    icon: "🧩",
    description: "Convert and format data between various formats.",
    tools: [
      {
        name: "Pdf to Markdown Converter",
        slug: "pdf-to-markdown-converter",
        icon: "📄➡️📝",
        description: "Convert PDF files to Markdown format.",
      },
      {
        name: "CSV to Markdown Converter",
        slug: "csv-to-markdown-converter",
        icon: "📄➡️📝",
        description: "Convert CSV files to Markdown tables.",
      },
      {
        name: "JSON to Markdown Converter",
        slug: "json-to-markdown-converter",
        icon: "🧩➡️📝",
        description: "Convert JSON data to Markdown format.",
      },
      {
        name: "DOCX to Markdown Converter",
        slug: "docx-to-markdown-converter",
        icon: "📄➡️📝",
        description: "Convert DOCX files to Markdown.",
      },
      {
        name: "HTML to Markdown Converter",
        slug: "html-to-markdown-converter",
        icon: "🌐➡️📝",
        description: "Convert HTML content to Markdown.",
      },
      {
        name: "Text to Markdown Converter",
        slug: "text-to-markdown-converter",
        icon: "📝➡️📝",
        description: "Convert plain text to Markdown format.",
      },
      {
        name: "Webpage to Markdown Converter",
        slug: "webpage-to-markdown-converter",
        icon: "🌐➡️📝",
        description: "Convert webpages to Markdown files.",
      },
      {
        name: "JSON Formatter & Validator",
        slug: "json-formatter-validator",
        icon: "🧾",
        description: "Format and validate JSON data.",
      },
      {
        name: "JSON Diff Viewer",
        slug: "json-diff",
        icon: "🆚",
        description: "Compare and view differences between JSON files.",
      },
      {
        name: "JSON Merge Tool",
        slug: "json-merge",
        icon: "🧬",
        description: "Merge multiple JSON files into one.",
      },
      {
        name: "JSON Minifier",
        slug: "json-minifier",
        icon: "📦",
        description: "Minify JSON data for compact storage.",
      },
      {
        name: "JSON Pretty Printer",
        slug: "json-pretty-print",
        icon: "🖨️",
        description: "Format JSON data for readability.",
      },
      {
        name: "JSON Schema Validator",
        slug: "json-schema-validator",
        icon: "✅",
        description: "Validate JSON data against a schema.",
      },
      {
        name: "CSV to JSON Converter",
        slug: "csv-to-json",
        icon: "🔁",
        description: "Convert CSV files to JSON format.",
      },
      {
        name: "JSON to CSV Converter",
        slug: "json-to-csv",
        icon: "🔁",
        description: "Convert JSON data to CSV files.",
      },
      {
        name: "YAML to JSON Converter",
        slug: "yaml-to-json",
        icon: "📄",
        description: "Convert YAML files to JSON format.",
      },
      {
        name: "JSON to YAML Converter",
        slug: "json-to-yaml",
        icon: "📄",
        description: "Convert JSON data to YAML format.",
      },
      {
        name: "XML Formatter",
        slug: "xml-formatter",
        icon: "🧷",
        description: "Format XML data for readability.",
      },
      {
        name: "XML to JSON Converter",
        slug: "xml-to-json",
        icon: "🔄",
        description: "Convert XML data to JSON format.",
      },
    ],
  },
  {
    name: "Encoding & Decoding",
    slug: "encoding-decoding",
    icon: "🔐",
    description: "Encode and decode data in various formats.",
    tools: [
      {
        name: "Base64 Encoder",
        slug: "base64-encode",
        icon: "🧬",
        description: "Encode data to Base64 format.",
      },
      {
        name: "Base64 Decoder",
        slug: "base64-decode",
        icon: "🧬",
        description: "Decode Base64 encoded data.",
      },
      {
        name: "URL Encoder",
        slug: "url-encode",
        icon: "🌐",
        description: "Encode URLs for safe transmission.",
      },
      {
        name: "URL Decoder",
        slug: "url-decode",
        icon: "🌐",
        description: "Decode encoded URLs.",
      },
      {
        name: "HTML Entity Encoder",
        slug: "html-entity-encode",
        icon: "🔣",
        description: "Encode special characters as HTML entities.",
      },
      {
        name: "HTML Entity Decoder",
        slug: "html-entity-decode",
        icon: "🔣",
        description: "Decode HTML entities to characters.",
      },
      {
        name: "JWT Decoder",
        slug: "jwt-decoder",
        icon: "🎫",
        description: "Decode and inspect JWT tokens.",
      },
      {
        name: "Gzip String Compressor",
        slug: "gzip-compressor",
        icon: "🗜️",
        description: "Compress strings using Gzip.",
      },
      {
        name: "Gzip String Decompressor",
        slug: "gzip-decompressor",
        icon: "🗜️",
        description: "Decompress Gzip-compressed strings.",
      },
      {
        name: "Morse Code Encoder",
        slug: "morse-encode",
        icon: "📡",
        description: "Encode text into Morse code.",
      },
    ],
  },
  // {
  //   name: "Time & Date",
  //   slug: "time-date",
  //   icon: "⏱️",
  //   tools: [
  //     { name: "Timestamp Converter", slug: "timestamp-converter", icon: "📅" },
  //     { name: "Current Unix Time", slug: "current-unix-time", icon: "⏰" },
  //     { name: "Timezone Converter", slug: "timezone-converter", icon: "🌍" },
  //     { name: "Cron Expression Parser", slug: "cron-parser", icon: "🧮" },
  //     { name: "Cron Expression Generator", slug: "cron-generator", icon: "🧩" },
  //     { name: "Date Difference Calculator", slug: "date-diff", icon: "➖" },
  //     { name: "ISO Date Formatter", slug: "iso-date-formatter", icon: "📆" },
  //     { name: "Countdown Generator", slug: "countdown-generator", icon: "⏳" },
  //     {
  //       name: "Working Days Calculator",
  //       slug: "working-days-calculator",
  //       icon: "📊",
  //     },
  //   ],
  // },
  // {
  //   name: "Text & Strings",
  //   slug: "text-strings",
  //   icon: "✏️",
  //   tools: [
  //     { name: "Text Cleaner", slug: "text-cleaner", icon: "🧼" },
  //     {
  //       name: "Word Cloud Generator",
  //       slug: "word-cloud-generator",
  //       icon: "☁️",
  //     },
  //     { name: "Text Reverser", slug: "text-reverser", icon: "🔄" },
  //     { name: "Case Converter", slug: "case-converter", icon: "🔤" },
  //     { name: "Text Diff Checker", slug: "text-diff", icon: "🧮" },
  //     { name: "Slug Generator", slug: "slug-generator", icon: "🏷️" },
  //     { name: "Word Counter", slug: "word-counter", icon: "📏" },
  //     { name: "Character Counter", slug: "character-counter", icon: "📏" },
  //     {
  //       name: "Duplicate Line Remover",
  //       slug: "duplicate-line-remover",
  //       icon: "🧹",
  //     },
  //     { name: "Line Sorter", slug: "line-sorter", icon: "↕️" },
  //     { name: "Whitespace Trimmer", slug: "whitespace-trimmer", icon: "✂️" },
  //     { name: "String Reverser", slug: "string-reverser", icon: "🔁" },
  //     { name: "Find & Replace Tool", slug: "find-replace", icon: "🔍" },
  //     { name: "URL Slug Cleaner", slug: "url-slug-cleaner", icon: "🧼" },
  //   ],
  // },
  // {
  //   name: "Images & Media",
  //   slug: "images-media",
  //   icon: "🖼️",
  //   tools: [
  //     { name: "Image Resizer", slug: "image-resizer", icon: "📏" },
  //     { name: "Image Compressor", slug: "image-compressor", icon: "🗜️" },
  //     { name: "PNG to JPG Converter", slug: "png-to-jpg", icon: "🖼️" },
  //     { name: "JPG to PNG Converter", slug: "jpg-to-png", icon: "🖼️" },
  //     { name: "SVG Optimizer", slug: "svg-optimizer", icon: "📐" },
  //     { name: "Favicon Generator", slug: "favicon-generator", icon: "🌟" },
  //     { name: "Image Cropper", slug: "image-cropper", icon: "✂️" },
  //     {
  //       name: "Image to Base64 Converter",
  //       slug: "image-to-base64",
  //       icon: "🧬",
  //     },
  //     {
  //       name: "Base64 to Image Converter",
  //       slug: "base64-to-image",
  //       icon: "🧬",
  //     },
  //     { name: "Video to GIF Converter", slug: "video-to-gif", icon: "🎞️" },
  //   ],
  // },
  // {
  //   name: "Networking",
  //   slug: "networking",
  //   icon: "🌐",
  //   tools: [
  //     { name: "IP Address Lookup", slug: "ip-lookup", icon: "📍" },
  //     { name: "DNS Lookup", slug: "dns-lookup", icon: "📡" },
  //     { name: "WHOIS Lookup", slug: "whois-lookup", icon: "🪪" },
  //     { name: "Ping Tester", slug: "ping-tester", icon: "📶" },
  //     { name: "HTTP Header Viewer", slug: "http-header-viewer", icon: "📨" },
  //     { name: "URL Parser", slug: "url-parser", icon: "🧩" },
  //     { name: "CIDR Calculator", slug: "cidr-calculator", icon: "📏" },
  //     { name: "MAC Address Lookup", slug: "mac-lookup", icon: "💻" },
  //     { name: "User-Agent Parser", slug: "user-agent-parser", icon: "🔍" },
  //   ],
  // },
  // {
  //   name: "Security",
  //   slug: "security",
  //   icon: "🛡️",
  //   tools: [
  //     { name: "Hash Generator (MD5/SHA)", slug: "hash-generator", icon: "🧮" },
  //     { name: "Bcrypt Hash Generator", slug: "bcrypt-generator", icon: "🔐" },
  //     { name: "JWT Debugger", slug: "jwt-debugger", icon: "🧪" },
  //     { name: "HMAC Generator", slug: "hmac-generator", icon: "📏" },
  //     { name: "PEM to JWK Converter", slug: "pem-to-jwk", icon: "🧷" },
  //     { name: "CSR Decoder", slug: "csr-decoder", icon: "📜" },
  //     { name: "Certificate Decoder", slug: "certificate-decoder", icon: "📄" },
  //   ],
  // },
  // {
  //   name: "Math & Calculators",
  //   slug: "math-calculators",
  //   icon: "➗",
  //   tools: [
  //     {
  //       name: "Percentage Calculator",
  //       slug: "percentage-calculator",
  //       icon: "📊",
  //     },
  //     { name: "Unit Converter", slug: "unit-converter", icon: "⚖️" },
  //     { name: "Number Base Converter", slug: "base-converter", icon: "🔢" },
  //     { name: "Simple Calculator", slug: "simple-calculator", icon: "🧮" },
  //     { name: "Loan Calculator", slug: "loan-calculator", icon: "🏦" },
  //     {
  //       name: "Compound Interest Calculator",
  //       slug: "compound-interest-calculator",
  //       icon: "📈",
  //     },
  //     {
  //       name: "Statistics Calculator",
  //       slug: "statistics-calculator",
  //       icon: "📉",
  //     },
  //     { name: "Matrix Calculator", slug: "matrix-calculator", icon: "🧊" },
  //   ],
  // },
  // {
  //   name: "Colors & Design",
  //   slug: "colors-design",
  //   icon: "🎨",
  //   tools: [
  //     { name: "Color Picker", slug: "color-picker", icon: "🎯" },
  //     { name: "Palette Generator", slug: "palette-generator", icon: "🌈" },
  //     { name: "Gradient Generator", slug: "gradient-generator", icon: "📶" },
  //     { name: "Contrast Checker", slug: "contrast-checker", icon: "🌓" },
  //     {
  //       name: "Box Shadow Generator",
  //       slug: "box-shadow-generator",
  //       icon: "📦",
  //     },
  //     {
  //       name: "Border Radius Generator",
  //       slug: "border-radius-generator",
  //       icon: "⭕",
  //     },
  //     {
  //       name: "CSS Clip-Path Generator",
  //       slug: "clip-path-generator",
  //       icon: "✂️",
  //     },
  //     {
  //       name: "Tailwind Color Explorer",
  //       slug: "tailwind-color-explorer",
  //       icon: "💠",
  //     },
  //     { name: "SVG Icon Previewer", slug: "svg-icon-previewer", icon: "🔍" },
  //   ],
  // },
  // {
  //   name: "Spinners Wheel",
  //   slug: "spinners-wheel",
  //   icon: "🎡",
  //   tools: [{ name: "Spinner Wheel", slug: "spinner-wheel", icon: "🎡" }],
  // },
  // {
  //   name: "Torrent & Hashing",
  //   slug: "torrent-hashing",
  //   icon: "📡",
  //   tools: [
  //     {
  //       name: "Magnet Link Generator",
  //       slug: "magnet-link-generator",
  //       icon: "🧲",
  //     },
  //     { name: "BTIH Hash Generator", slug: "btih-hash-generator", icon: "🔢" },
  //     { name: "Torrent File Parser", slug: "torrent-file-parser", icon: "📂" },
  //     {
  //       name: "Torrent File Creator",
  //       slug: "torrent-file-creator",
  //       icon: "🛠️",
  //     },
  //     { name: "Info Hash Extractor", slug: "info-hash-extractor", icon: "🔍" },
  //   ],
  // },
];
