export const categories = [
  {
    name: "Trending Tools",
    slug: "trending-tools",
    icon: "🎲",
    tools: [
      { name: "QR Code Generator", slug: "qr-code-generator", icon: "� QR" },
      {
        name: "Random Password Generator",
        slug: "random-password-generator",
        icon: "🔑",
      },
      {
        name: "Random Name Generator",
        slug: "random-name-generator",
        icon: "🧑‍🤝‍🧑",
      },
      {
        name: "Last Name Generator",
        slug: "last-name-generator",
        icon: "👤",
      },

      {
        name: "Random Username Generator",
        slug: "random-username-generator",
        icon: "👤",
      },
      {
        name: "Random Choice Picker",
        slug: "random-choice-picker",
        icon: "🎲",
      },
      {
        name: "Random Number Generator",
        slug: "random-number-generator",
        icon: "🎲",
      },
      {
        name: "Lorem Ipsum Generator",
        slug: "lorem-ipsum-generator",
        icon: "📜",
      },
    ],
  },
  {
    name: "Ai Generators",
    slug: "ai-generators",
    icon: "🤖",
    tools: [
      { name: "AI Reply Generator", slug: "ai-reply-generator", icon: "💬" },
      { name: "Ai Prompt Generator", slug: "ai-prompt-generator", icon: "🧠" },
      { name: "AI Prompt Optimizer", slug: "ai-prompt-optimizer", icon: "⚙️" },
      { name: "AI Faq Generator", slug: "ai-faq-generator", icon: "❓" },
      { name: "AI Answer Generator", slug: "ai-answer-generator", icon: "🅰️" },
      {
        name: "AI Email Response Generator",
        slug: "ai-email-response-generator",
        icon: "📧",
      },
      {
        name: "Ai Letter Generator",
        slug: "ai-letter-generator",
        icon: "✉️",
      },
      {
        name: "AI Blog title Generator",
        slug: "ai-blog-title-generator",
        icon: "📝",
      },
      {
        name: "AI Saas Name Generator",
        slug: "ai-saas-name-generator",
        icon: "💡",
      },
    ],
  },
  {
    name: "Generators",
    slug: "generators",
    icon: "⚙️",
    tools: [
      { name: "UUID Generator", slug: "uuid-generator", icon: "🎲" },
      { name: "NanoID Generator", slug: "nanoid-generator", icon: "🧬" },
      { name: "Fake Data Generator", slug: "fake-data-generator", icon: "🧪" },
      { name: "Changelog Generator", slug: "changelog-generator", icon: "📑" },
    ],
  },
  // {
  //   name: "Finance Calculators",
  //   slug: "finance-calculators",
  //   icon: "💵",
  //   tools: [
  //     { name: "Mortgage Calculator", slug: "mortgage-calculator", icon: "🏠" },
  //     {
  //       name: "Retirement Calculator",
  //       slug: "retirement-calculator",
  //       icon: "🏖️",
  //     },
  //     { name: "Savings Calculator", slug: "savings-calculator", icon: "💰" },
  //   ],
  // },
  // {
  //   name: "Business & Finance",
  //   slug: "business-finance",
  //   icon: "💼",
  //   tools: [
  //     { name: "Invoice Generator", slug: "invoice-generator", icon: "🧾" },
  //     {
  //       name: "Business Name Generator",
  //       slug: "business-name-generator",
  //       icon: "🏢",
  //     },
  //     { name: "SWOT Analysis Generator", slug: "swot-generator", icon: "📊" },
  // { name: "Pitch Deck Generator", slug: "pitch-deck-generator", icon: "📈" },
  // {
  //   name: "Business Idea Generator",
  //   slug: "business-idea-generator",
  //   icon: "💡",
  // },
  // { name: "Pdf to Faq Generator", slug: "pdf-to-faq-generator", icon: "📄❓" },
  // {
  //   name: "Webpage to Faq Generator",
  //   slug: "webpage-to-faq-generator",
  //   icon: "🌐❓",
  // },
  //   ],
  // },
  // {
  //   name: "Health & Fitness",
  //   slug: "health-fitness",
  //   icon: "💪",
  //   tools: [
  //     { name: "BMI Calculator", slug: "bmi-calculator", icon: "⚖️" },
  //     { name: "Calorie Tracker", slug: "calorie-tracker", icon: "🍎" },
  //     { name: "Water Intake Calculator", slug: "water-intake", icon: "💧" },
  //   ],
  // },
  // {
  //   name: "Writing & Content Creation",
  //   slug: "writing-content-creation",
  //   icon: "✍️",
  //   tools: [
  //     { name: "Grammar Checker", slug: "grammar-checker", icon: "📝" },
  //     { name: "Plagiarism Detector", slug: "plagiarism-detector", icon: "🔍" },
  //     { name: "Language Translator", slug: "language-translator", icon: "🌐" },
  //   ],
  // },
  // {
  //   name: "Productivity & Utilities",
  //   slug: "productivity-utilities",
  //   icon: "⚙️",
  //   tools: [
  //     { name: "Text Expander", slug: "text-expander", icon: "✍️" },
  //     { name: "Task Manager", slug: "task-manager", icon: "✅" },
  //     { name: "Pomodoro Timer", slug: "pomodoro-timer", icon: "⏲️" },
  //     { name: "Note Taker", slug: "note-taker", icon: "🗒️" },
  //   ],
  // },
  // {
  //   name: "Mindfulness & Relaxation",
  //   slug: "mindfulness-relaxation",
  //   icon: "🧘‍♂️",
  //   tools: [
  //     { name: "Breathing Exercise", slug: "breathing-exercise", icon: "🌬️" },
  //     { name: "Guided Meditation", slug: "guided-meditation", icon: "🧘‍♀️" },
  //     { name: "Sleep Sounds", slug: "sleep-sounds", icon: "😴" },
  //   ],
  // },
  // {
  //   name: "Text Analysis & Manipulation",
  //   slug: "text-analysis-manipulation",
  //   icon: "📝",
  //   tools: [
  //     { name: "Sentiment Analyzer", slug: "sentiment-analyzer", icon: "😊" },
  //     { name: "Readability Checker", slug: "readability-checker", icon: "📖" },
  //     { name: "Keyword Extractor", slug: "keyword-extractor", icon: "🔑" },
  //   ],
  // },
  // {
  //   name: "Code & Development",
  //   slug: "code-development",
  //   icon: "💻",
  //   tools: [
  //     { name: "Code Beautifier", slug: "code-beautifier", icon: "🧼" },
  //     { name: "Minify JavaScript", slug: "minify-javascript", icon: "🗜️" },
  //     { name: "HTML Formatter", slug: "html-formatter", icon: "🌐" },
  //     { name: "CSS Formatter", slug: "css-formatter", icon: "🎨" },
  //   ],
  // },
  // {
  //   name: "File and Data Conversion",
  //   slug: "file-data-conversion",
  //   icon: "🔄",
  //   tools: [
  //     { name: "Text to PDF Converter", slug: "text-to-pdf", icon: "📄" },
  //     { name: "PDF to Text Converter", slug: "pdf-to-text", icon: "📄" },
  //     { name: "Image to PDF Converter", slug: "image-to-pdf", icon: "🖼️" },
  //   ],
  // },
  {
    name: "Website & SEO",
    slug: "website-seo",
    icon: "🌐",
    tools: [
      { name: "Meta Tag Generator", slug: "meta-tag-generator", icon: "🏷️" },
      { name: "Hashtag Generator", slug: "hashtag-generator", icon: "🏷️" },
      {
        name: "Sitemap Finder and Checker",
        slug: "sitemap-finder-checker",
        icon: "🗺️",
      },
      { name: "Sitemap Generator", slug: "sitemap-generator", icon: "🗺️" },
      {
        name: "XML Sitemap Generator",
        slug: "xml-sitemap-generator",
        icon: "🗺️",
      },
      { name: "Sitemap Validator", slug: "sitemap-validator", icon: "✅" },
      {
        name: "robots.txt Generator",
        slug: "robots-txt-generator",
        icon: "🤖",
      },
      {
        name: "OpenAPI Stub Generator",
        slug: "openapi-stub-generator",
        icon: "📘",
      },
      { name: "README Generator", slug: "readme-generator", icon: "📖" },
    ],
  },
  {
    name: "Data Conversion & Formatting",
    slug: "data-convertor",
    icon: "🧩",
    tools: [
      {
        name: "Pdf to Markdown Converter",
        slug: "pdf-to-markdown-converter",
        icon: "📄➡️📝",
      },
      {
        name: "CSV to Markdown Converter",
        slug: "csv-to-markdown-converter",
        icon: "📄➡️📝",
      },
      {
        name: "JSON to Markdown Converter",
        slug: "json-to-markdown-converter",
        icon: "🧩➡️📝",
      },
      {
        name: "DOCX to Markdown Converter",
        slug: "docx-to-markdown-converter",
        icon: "📄➡️📝",
      },
      {
        name: "HTML to Markdown Converter",
        slug: "html-to-markdown-converter",
        icon: "🌐➡️📝",
      },
      {
        name: "Text to Markdown Converter",
        slug: "text-to-markdown-converter",
        icon: "📝➡️📝",
      },
      {
        name: "Webpage to Markdown Converter",
        slug: "webpage-to-markdown-converter",
        icon: "🌐➡️📝",
      },
      {
        name: "Notion to Markdown Converter",
        slug: "notion-to-markdown-converter",
        icon: "🗒️➡️📝",
      },
      {
        name: "JSON Formatter & Validator",
        slug: "json-formatter-validator",
        icon: "🧾",
      },
      { name: "JSON Minifier", slug: "json-minifier", icon: "📦" },
      { name: "JSON Pretty Printer", slug: "json-pretty-print", icon: "🖨️" },
      {
        name: "JSON Schema Validator",
        slug: "json-schema-validator",
        icon: "✅",
      },
      { name: "CSV to JSON Converter", slug: "csv-to-json", icon: "🔁" },
      { name: "JSON to CSV Converter", slug: "json-to-csv", icon: "🔁" },
      { name: "YAML to JSON Converter", slug: "yaml-to-json", icon: "📄" },
      { name: "JSON to YAML Converter", slug: "json-to-yaml", icon: "📄" },
      { name: "XML Formatter", slug: "xml-formatter", icon: "🧷" },
      { name: "XML to JSON Converter", slug: "xml-to-json", icon: "🔄" },
      { name: "INI to JSON Converter", slug: "ini-to-json", icon: "⚙️" },
      { name: "TOML to JSON Converter", slug: "toml-to-json", icon: "📚" },
      { name: "JSON Diff Viewer", slug: "json-diff", icon: "🆚" },
      { name: "JSON Path Tester", slug: "jsonpath-tester", icon: "🔍" },
      { name: "JSON Merge Tool", slug: "json-merge", icon: "🧬" },
    ],
  },
  {
    name: "Encoding & Decoding",
    slug: "encoding-decoding",
    icon: "🔐",
    tools: [
      { name: "Base64 Encoder", slug: "base64-encode", icon: "🧬" },
      { name: "Base64 Decoder", slug: "base64-decode", icon: "🧬" },
      { name: "URL Encoder", slug: "url-encode", icon: "🌐" },
      { name: "URL Decoder", slug: "url-decode", icon: "🌐" },
      { name: "HTML Entity Encoder", slug: "html-entity-encode", icon: "🔣" },
      { name: "HTML Entity Decoder", slug: "html-entity-decode", icon: "🔣" },
      { name: "JWT Decoder", slug: "jwt-decoder", icon: "🎫" },
      { name: "Gzip String Compressor", slug: "gzip-compressor", icon: "🗜️" },
      {
        name: "Gzip String Decompressor",
        slug: "gzip-decompressor",
        icon: "🗜️",
      },
      { name: "Morse Code Encoder", slug: "morse-encode", icon: "📡" },
    ],
  },
  // {
  //   name: "Time & Date",
  //   slug: "time-date",
  //   icon: "⏱️",
  //   tools: [
  //     { name: "Timestamp Converter", slug: "timestamp-converter", icon: "📅" },
  //     { name: "Current Unix Time", slug: "current-unix-time", icon: "⏰" },
  //     { name: "Timezone Converter", slug: "timezone-converter", icon: "🌍" },
  //     { name: "Cron Expression Parser", slug: "cron-parser", icon: "🧮" },
  //     { name: "Cron Expression Generator", slug: "cron-generator", icon: "🧩" },
  //     { name: "Date Difference Calculator", slug: "date-diff", icon: "➖" },
  //     { name: "ISO Date Formatter", slug: "iso-date-formatter", icon: "📆" },
  //     { name: "Countdown Generator", slug: "countdown-generator", icon: "⏳" },
  //     {
  //       name: "Working Days Calculator",
  //       slug: "working-days-calculator",
  //       icon: "📊",
  //     },
  //   ],
  // },
  // {
  //   name: "Text & Strings",
  //   slug: "text-strings",
  //   icon: "✏️",
  //   tools: [
  //     { name: "Text Cleaner", slug: "text-cleaner", icon: "🧼" },
  //     {
  //       name: "Word Cloud Generator",
  //       slug: "word-cloud-generator",
  //       icon: "☁️",
  //     },
  //     { name: "Text Reverser", slug: "text-reverser", icon: "🔄" },
  //     { name: "Case Converter", slug: "case-converter", icon: "🔤" },
  //     { name: "Text Diff Checker", slug: "text-diff", icon: "🧮" },
  //     { name: "Slug Generator", slug: "slug-generator", icon: "🏷️" },
  //     { name: "Word Counter", slug: "word-counter", icon: "📏" },
  //     { name: "Character Counter", slug: "character-counter", icon: "📏" },
  //     {
  //       name: "Duplicate Line Remover",
  //       slug: "duplicate-line-remover",
  //       icon: "🧹",
  //     },
  //     { name: "Line Sorter", slug: "line-sorter", icon: "↕️" },
  //     { name: "Whitespace Trimmer", slug: "whitespace-trimmer", icon: "✂️" },
  //     { name: "String Reverser", slug: "string-reverser", icon: "🔁" },
  //     { name: "Find & Replace Tool", slug: "find-replace", icon: "🔍" },
  //     { name: "URL Slug Cleaner", slug: "url-slug-cleaner", icon: "🧼" },
  //   ],
  // },
  // {
  //   name: "Images & Media",
  //   slug: "images-media",
  //   icon: "🖼️",
  //   tools: [
  //     { name: "Image Resizer", slug: "image-resizer", icon: "📏" },
  //     { name: "Image Compressor", slug: "image-compressor", icon: "🗜️" },
  //     { name: "PNG to JPG Converter", slug: "png-to-jpg", icon: "🖼️" },
  //     { name: "JPG to PNG Converter", slug: "jpg-to-png", icon: "🖼️" },
  //     { name: "SVG Optimizer", slug: "svg-optimizer", icon: "📐" },
  //     { name: "Favicon Generator", slug: "favicon-generator", icon: "🌟" },
  //     { name: "Image Cropper", slug: "image-cropper", icon: "✂️" },
  //     {
  //       name: "Image to Base64 Converter",
  //       slug: "image-to-base64",
  //       icon: "🧬",
  //     },
  //     {
  //       name: "Base64 to Image Converter",
  //       slug: "base64-to-image",
  //       icon: "🧬",
  //     },
  //     { name: "Video to GIF Converter", slug: "video-to-gif", icon: "🎞️" },
  //   ],
  // },
  // {
  //   name: "Networking",
  //   slug: "networking",
  //   icon: "🌐",
  //   tools: [
  //     { name: "IP Address Lookup", slug: "ip-lookup", icon: "📍" },
  //     { name: "DNS Lookup", slug: "dns-lookup", icon: "📡" },
  //     { name: "WHOIS Lookup", slug: "whois-lookup", icon: "🪪" },
  //     { name: "Ping Tester", slug: "ping-tester", icon: "📶" },
  //     { name: "HTTP Header Viewer", slug: "http-header-viewer", icon: "📨" },
  //     { name: "URL Parser", slug: "url-parser", icon: "🧩" },
  //     { name: "CIDR Calculator", slug: "cidr-calculator", icon: "📏" },
  //     { name: "MAC Address Lookup", slug: "mac-lookup", icon: "💻" },
  //     { name: "User-Agent Parser", slug: "user-agent-parser", icon: "🔍" },
  //   ],
  // },
  // {
  //   name: "Security",
  //   slug: "security",
  //   icon: "🛡️",
  //   tools: [
  //     { name: "Hash Generator (MD5/SHA)", slug: "hash-generator", icon: "🧮" },
  //     { name: "Bcrypt Hash Generator", slug: "bcrypt-generator", icon: "🔐" },
  //     { name: "JWT Debugger", slug: "jwt-debugger", icon: "🧪" },
  //     { name: "HMAC Generator", slug: "hmac-generator", icon: "📏" },
  //     { name: "PEM to JWK Converter", slug: "pem-to-jwk", icon: "🧷" },
  //     { name: "CSR Decoder", slug: "csr-decoder", icon: "📜" },
  //     { name: "Certificate Decoder", slug: "certificate-decoder", icon: "📄" },
  //   ],
  // },
  // {
  //   name: "Math & Calculators",
  //   slug: "math-calculators",
  //   icon: "➗",
  //   tools: [
  //     {
  //       name: "Percentage Calculator",
  //       slug: "percentage-calculator",
  //       icon: "📊",
  //     },
  //     { name: "Unit Converter", slug: "unit-converter", icon: "⚖️" },
  //     { name: "Number Base Converter", slug: "base-converter", icon: "🔢" },
  //     { name: "Simple Calculator", slug: "simple-calculator", icon: "🧮" },
  //     { name: "Loan Calculator", slug: "loan-calculator", icon: "🏦" },
  //     {
  //       name: "Compound Interest Calculator",
  //       slug: "compound-interest-calculator",
  //       icon: "📈",
  //     },
  //     {
  //       name: "Statistics Calculator",
  //       slug: "statistics-calculator",
  //       icon: "📉",
  //     },
  //     { name: "Matrix Calculator", slug: "matrix-calculator", icon: "🧊" },
  //   ],
  // },
  // {
  //   name: "Colors & Design",
  //   slug: "colors-design",
  //   icon: "🎨",
  //   tools: [
  //     { name: "Color Picker", slug: "color-picker", icon: "🎯" },
  //     { name: "Palette Generator", slug: "palette-generator", icon: "🌈" },
  //     { name: "Gradient Generator", slug: "gradient-generator", icon: "📶" },
  //     { name: "Contrast Checker", slug: "contrast-checker", icon: "🌓" },
  //     {
  //       name: "Box Shadow Generator",
  //       slug: "box-shadow-generator",
  //       icon: "📦",
  //     },
  //     {
  //       name: "Border Radius Generator",
  //       slug: "border-radius-generator",
  //       icon: "⭕",
  //     },
  //     {
  //       name: "CSS Clip-Path Generator",
  //       slug: "clip-path-generator",
  //       icon: "✂️",
  //     },
  //     {
  //       name: "Tailwind Color Explorer",
  //       slug: "tailwind-color-explorer",
  //       icon: "💠",
  //     },
  //     { name: "SVG Icon Previewer", slug: "svg-icon-previewer", icon: "🔍" },
  //   ],
  // },
  // {
  //   name: "Spinners Wheel",
  //   slug: "spinners-wheel",
  //   icon: "🎡",
  //   tools: [{ name: "Spinner Wheel", slug: "spinner-wheel", icon: "🎡" }],
  // },
  // {
  //   name: "Torrent & Hashing",
  //   slug: "torrent-hashing",
  //   icon: "📡",
  //   tools: [
  //     {
  //       name: "Magnet Link Generator",
  //       slug: "magnet-link-generator",
  //       icon: "🧲",
  //     },
  //     { name: "BTIH Hash Generator", slug: "btih-hash-generator", icon: "🔢" },
  //     { name: "Torrent File Parser", slug: "torrent-file-parser", icon: "📂" },
  //     {
  //       name: "Torrent File Creator",
  //       slug: "torrent-file-creator",
  //       icon: "🛠️",
  //     },
  //     { name: "Info Hash Extractor", slug: "info-hash-extractor", icon: "🔍" },
  //   ],
  // },
];
