import React from "react";
import RandomAnimalGen from "./RandomAnimalGen";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Random Animal Generator - Create Unique Animal Names | ToolsBase",
  description:
    " Generate random and unique animal names with our Random Animal Generator. Perfect for writers, gamers, and creatives looking for inspiration. Try it now!",
  keywords: [
    "random animal generator",
    "animal name generator",
    "unique animal names",
    "creative animal names",
  ],
  publisher: "ToolsBase Network",
  metadataBase: new URL("https://toolsbase.org"),
  alternates: { canonical: "/randomisers/random-animal-generator" },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
};

const Animals = [
  {
    Animal: "Lion",
    Diet: "Carnivore",
    Habitat: "Savanna",
    Lifespan: "10-14 years",
    Weight: "190 kg",
    ImageURL: "https://example.com/images/lion.jpg",
  },
  {
    Animal: "Tiger",
    Diet: "Carnivore",
    Habitat: "Forest",
    Lifespan: "8-12 years",
    Weight: "220 kg",
    ImageURL: "https://example.com/images/tiger.jpg",
  },
  {
    Animal: "Elephant",
    Diet: "Herbivore",
    Habitat: "Grassland",
    Lifespan: "60-70 years",
    Weight: "6000 kg",
    ImageURL: "https://example.com/images/elephant.jpg",
  },
  {
    Animal: "Giraffe",
    Diet: "Herbivore",
    Habitat: "Savanna",
    Lifespan: "25 years",
    Weight: "800 kg",
    ImageURL: "https://example.com/images/giraffe.jpg",
  },
  {
    Animal: "Zebra",
    Diet: "Herbivore",
    Habitat: "Grassland",
    Lifespan: "20-25 years",
    Weight: "350 kg",
    ImageURL: "https://example.com/images/zebra.jpg",
  },
  {
    Animal: "Wolf",
    Diet: "Carnivore",
    Habitat: "Forest",
    Lifespan: "8-13 years",
    Weight: "45 kg",
    ImageURL: "https://example.com/images/wolf.jpg",
  },
  {
    Animal: "Bear",
    Diet: "Omnivore",
    Habitat: "Forest",
    Lifespan: "20-30 years",
    Weight: "300 kg",
    ImageURL: "https://example.com/images/bear.jpg",
  },
  {
    Animal: "Kangaroo",
    Diet: "Herbivore",
    Habitat: "Grassland",
    Lifespan: "20 years",
    Weight: "85 kg",
    ImageURL: "https://example.com/images/kangaroo.jpg",
  },
  {
    Animal: "Panda",
    Diet: "Herbivore",
    Habitat: "Forest",
    Lifespan: "20 years",
    Weight: "100 kg",
    ImageURL: "https://example.com/images/panda.jpg",
  },
  {
    Animal: "Eagle",
    Diet: "Carnivore",
    Habitat: "Mountains",
    Lifespan: "20-30 years",
    Weight: "6 kg",
    ImageURL: "https://example.com/images/eagle.jpg",
  },
  {
    Animal: "Leopard",
    Diet: "Carnivore",
    Habitat: "Forest",
    Lifespan: "12-17 years",
    Weight: "90 kg",
    ImageURL: "https://example.com/images/leopard.jpg",
  },
  {
    Animal: "Cheetah",
    Diet: "Carnivore",
    Habitat: "Grassland",
    Lifespan: "10-12 years",
    Weight: "72 kg",
    ImageURL: "https://example.com/images/cheetah.jpg",
  },
  {
    Animal: "Hyena",
    Diet: "Carnivore",
    Habitat: "Savanna",
    Lifespan: "12-25 years",
    Weight: "60 kg",
    ImageURL: "https://example.com/images/hyena.jpg",
  },
  {
    Animal: "Rhinoceros",
    Diet: "Herbivore",
    Habitat: "Grassland",
    Lifespan: "40-50 years",
    Weight: "2300 kg",
    ImageURL: "https://example.com/images/rhinoceros.jpg",
  },
  {
    Animal: "Hippopotamus",
    Diet: "Herbivore",
    Habitat: "River",
    Lifespan: "40-50 years",
    Weight: "1500 kg",
    ImageURL: "https://example.com/images/hippopotamus.jpg",
  },
  {
    Animal: "Crocodile",
    Diet: "Carnivore",
    Habitat: "Wetlands",
    Lifespan: "70 years",
    Weight: "1000 kg",
    ImageURL: "https://example.com/images/crocodile.jpg",
  },
  {
    Animal: "Alligator",
    Diet: "Carnivore",
    Habitat: "Swamp",
    Lifespan: "35-50 years",
    Weight: "360 kg",
    ImageURL: "https://example.com/images/alligator.jpg",
  },
  {
    Animal: "Chimpanzee",
    Diet: "Omnivore",
    Habitat: "Forest",
    Lifespan: "40-50 years",
    Weight: "50 kg",
    ImageURL: "https://example.com/images/chimpanzee.jpg",
  },
  {
    Animal: "Gorilla",
    Diet: "Herbivore",
    Habitat: "Forest",
    Lifespan: "35-40 years",
    Weight: "160 kg",
    ImageURL: "https://example.com/images/gorilla.jpg",
  },
  {
    Animal: "Orangutan",
    Diet: "Omnivore",
    Habitat: "Rainforest",
    Lifespan: "35-45 years",
    Weight: "90 kg",
    ImageURL: "https://example.com/images/orangutan.jpg",
  },
  {
    Animal: "Baboon",
    Diet: "Omnivore",
    Habitat: "Savanna",
    Lifespan: "30 years",
    Weight: "40 kg",
    ImageURL: "https://example.com/images/baboon.jpg",
  },
  {
    Animal: "Meerkat",
    Diet: "Omnivore",
    Habitat: "Desert",
    Lifespan: "12-14 years",
    Weight: "1 kg",
    ImageURL: "https://example.com/images/meerkat.jpg",
  },
  {
    Animal: "Otter",
    Diet: "Carnivore",
    Habitat: "River",
    Lifespan: "10-15 years",
    Weight: "14 kg",
    ImageURL: "https://example.com/images/otter.jpg",
  },
  {
    Animal: "Beaver",
    Diet: "Herbivore",
    Habitat: "River",
    Lifespan: "10-12 years",
    Weight: "24 kg",
    ImageURL: "https://example.com/images/beaver.jpg",
  },
  {
    Animal: "Porcupine",
    Diet: "Herbivore",
    Habitat: "Forest",
    Lifespan: "15 years",
    Weight: "12 kg",
    ImageURL: "https://example.com/images/porcupine.jpg",
  },
  {
    Animal: "Skunk",
    Diet: "Omnivore",
    Habitat: "Forest",
    Lifespan: "7-10 years",
    Weight: "5 kg",
    ImageURL: "https://example.com/images/skunk.jpg",
  },
  {
    Animal: "Raccoon",
    Diet: "Omnivore",
    Habitat: "Forest",
    Lifespan: "8-12 years",
    Weight: "9 kg",
    ImageURL: "https://example.com/images/raccoon.jpg",
  },
  {
    Animal: "Armadillo",
    Diet: "Omnivore",
    Habitat: "Grassland",
    Lifespan: "12-15 years",
    Weight: "6 kg",
    ImageURL: "https://example.com/images/armadillo.jpg",
  },
  {
    Animal: "Sloth",
    Diet: "Herbivore",
    Habitat: "Rainforest",
    Lifespan: "20-30 years",
    Weight: "4 kg",
    ImageURL: "https://example.com/images/sloth.jpg",
  },
  {
    Animal: "Anteater",
    Diet: "Insectivore",
    Habitat: "Grassland",
    Lifespan: "14 years",
    Weight: "40 kg",
    ImageURL: "https://example.com/images/anteater.jpg",
  },
  {
    Animal: "Moose",
    Diet: "Herbivore",
    Habitat: "Forest",
    Lifespan: "15-25 years",
    Weight: "500 kg",
    ImageURL: "https://example.com/images/moose.jpg",
  },
  {
    Animal: "Elk",
    Diet: "Herbivore",
    Habitat: "Forest",
    Lifespan: "10-20 years",
    Weight: "320 kg",
    ImageURL: "https://example.com/images/elk.jpg",
  },
  {
    Animal: "Reindeer",
    Diet: "Herbivore",
    Habitat: "Tundra",
    Lifespan: "15-20 years",
    Weight: "160 kg",
    ImageURL: "https://example.com/images/reindeer.jpg",
  },
  {
    Animal: "Bison",
    Diet: "Herbivore",
    Habitat: "Grassland",
    Lifespan: "15-20 years",
    Weight: "900 kg",
    ImageURL: "https://example.com/images/bison.jpg",
  },
  {
    Animal: "Yak",
    Diet: "Herbivore",
    Habitat: "Mountains",
    Lifespan: "20-25 years",
    Weight: "500 kg",
    ImageURL: "https://example.com/images/yak.jpg",
  },
  {
    Animal: "Ibex",
    Diet: "Herbivore",
    Habitat: "Mountains",
    Lifespan: "15-17 years",
    Weight: "90 kg",
    ImageURL: "https://example.com/images/ibex.jpg",
  },
  {
    Animal: "Mountain Goat",
    Diet: "Herbivore",
    Habitat: "Mountains",
    Lifespan: "12-15 years",
    Weight: "115 kg",
    ImageURL: "https://example.com/images/mountain-goat.jpg",
  },
  {
    Animal: "Sheep",
    Diet: "Herbivore",
    Habitat: "Grassland",
    Lifespan: "10-12 years",
    Weight: "80 kg",
    ImageURL: "https://example.com/images/sheep.jpg",
  },
  {
    Animal: "Goat",
    Diet: "Herbivore",
    Habitat: "Grassland",
    Lifespan: "12-15 years",
    Weight: "60 kg",
    ImageURL: "https://example.com/images/goat.jpg",
  },
  {
    Animal: "Cow",
    Diet: "Herbivore",
    Habitat: "Grassland",
    Lifespan: "18-22 years",
    Weight: "700 kg",
    ImageURL: "https://example.com/images/cow.jpg",
  },
  {
    Animal: "Horse",
    Diet: "Herbivore",
    Habitat: "Grassland",
    Lifespan: "25-30 years",
    Weight: "500 kg",
    ImageURL: "https://example.com/images/horse.jpg",
  },
  {
    Animal: "Donkey",
    Diet: "Herbivore",
    Habitat: "Grassland",
    Lifespan: "25-30 years",
    Weight: "250 kg",
    ImageURL: "https://example.com/images/donkey.jpg",
  },
  {
    Animal: "Camel",
    Diet: "Herbivore",
    Habitat: "Desert",
    Lifespan: "40-50 years",
    Weight: "600 kg",
    ImageURL: "https://example.com/images/camel.jpg",
  },
  {
    Animal: "Llama",
    Diet: "Herbivore",
    Habitat: "Mountains",
    Lifespan: "15-25 years",
    Weight: "170 kg",
    ImageURL: "https://example.com/images/llama.jpg",
  },
  {
    Animal: "Alpaca",
    Diet: "Herbivore",
    Habitat: "Mountains",
    Lifespan: "15-20 years",
    Weight: "70 kg",
    ImageURL: "https://example.com/images/alpaca.jpg",
  },
  {
    Animal: "Pig",
    Diet: "Omnivore",
    Habitat: "Grassland",
    Lifespan: "15-20 years",
    Weight: "200 kg",
    ImageURL: "https://example.com/images/pig.jpg",
  },
  {
    Animal: "Boar",
    Diet: "Omnivore",
    Habitat: "Forest",
    Lifespan: "10-14 years",
    Weight: "180 kg",
    ImageURL: "https://example.com/images/boar.jpg",
  },
  {
    Animal: "Deer",
    Diet: "Herbivore",
    Habitat: "Forest",
    Lifespan: "10-20 years",
    Weight: "150 kg",
    ImageURL: "https://example.com/images/deer.jpg",
  },
  {
    Animal: "Antelope",
    Diet: "Herbivore",
    Habitat: "Savanna",
    Lifespan: "10-15 years",
    Weight: "120 kg",
    ImageURL: "https://example.com/images/antelope.jpg",
  },
  {
    Animal: "Gazelle",
    Diet: "Herbivore",
    Habitat: "Savanna",
    Lifespan: "10-12 years",
    Weight: "60 kg",
    ImageURL: "https://example.com/images/gazelle.jpg",
  },
  {
    Animal: "Okapi",
    Diet: "Herbivore",
    Habitat: "Rainforest",
    Lifespan: "20-30 years",
    Weight: "250 kg",
    ImageURL: "https://example.com/images/okapi.jpg",
  },
  {
    Animal: "Polar Bear",
    Diet: "Carnivore",
    Habitat: "Arctic",
    Lifespan: "20-30 years",
    Weight: "450 kg",
    ImageURL: "https://example.com/images/polar-bear.jpg",
  },
  {
    Animal: "Arctic Fox",
    Diet: "Omnivore",
    Habitat: "Arctic",
    Lifespan: "10-15 years",
    Weight: "9 kg",
    ImageURL: "https://example.com/images/arctic-fox.jpg",
  },
  {
    Animal: "Red Fox",
    Diet: "Omnivore",
    Habitat: "Forest",
    Lifespan: "8-12 years",
    Weight: "7 kg",
    ImageURL: "https://example.com/images/red-fox.jpg",
  },
  {
    Animal: "Snow Leopard",
    Diet: "Carnivore",
    Habitat: "Mountains",
    Lifespan: "15-18 years",
    Weight: "55 kg",
    ImageURL: "https://example.com/images/snow-leopard.jpg",
  },
  {
    Animal: "Cougar",
    Diet: "Carnivore",
    Habitat: "Mountains",
    Lifespan: "8-13 years",
    Weight: "80 kg",
    ImageURL: "https://example.com/images/cougar.jpg",
  },
  {
    Animal: "Lynx",
    Diet: "Carnivore",
    Habitat: "Forest",
    Lifespan: "10-15 years",
    Weight: "25 kg",
    ImageURL: "https://example.com/images/lynx.jpg",
  },
  {
    Animal: "Bobcat",
    Diet: "Carnivore",
    Habitat: "Forest",
    Lifespan: "10-12 years",
    Weight: "14 kg",
    ImageURL: "https://example.com/images/bobcat.jpg",
  },
  {
    Animal: "Jaguar",
    Diet: "Carnivore",
    Habitat: "Rainforest",
    Lifespan: "12-15 years",
    Weight: "100 kg",
    ImageURL: "https://example.com/images/jaguar.jpg",
  },
  {
    Animal: "Panther",
    Diet: "Carnivore",
    Habitat: "Forest",
    Lifespan: "12-17 years",
    Weight: "90 kg",
    ImageURL: "https://example.com/images/panther.jpg",
  },
  {
    Animal: "Ocelot",
    Diet: "Carnivore",
    Habitat: "Rainforest",
    Lifespan: "15-20 years",
    Weight: "15 kg",
    ImageURL: "https://example.com/images/ocelot.jpg",
  },
  {
    Animal: "Serval",
    Diet: "Carnivore",
    Habitat: "Grassland",
    Lifespan: "12-20 years",
    Weight: "18 kg",
    ImageURL: "https://example.com/images/serval.jpg",
  },
  {
    Animal: "Caracal",
    Diet: "Carnivore",
    Habitat: "Savanna",
    Lifespan: "12-15 years",
    Weight: "20 kg",
    ImageURL: "https://example.com/images/caracal.jpg",
  },
  {
    Animal: "Golden Jackal",
    Diet: "Omnivore",
    Habitat: "Grassland",
    Lifespan: "8-12 years",
    Weight: "15 kg",
    ImageURL: "https://example.com/images/golden-jackal.jpg",
  },
  {
    Animal: "African Wild Dog",
    Diet: "Carnivore",
    Habitat: "Savanna",
    Lifespan: "10-12 years",
    Weight: "30 kg",
    ImageURL: "https://example.com/images/african-wild-dog.jpg",
  },
  {
    Animal: "Dingo",
    Diet: "Carnivore",
    Habitat: "Desert",
    Lifespan: "10-13 years",
    Weight: "20 kg",
    ImageURL: "https://example.com/images/dingo.jpg",
  },
  {
    Animal: "Coyote",
    Diet: "Omnivore",
    Habitat: "Grassland",
    Lifespan: "10-14 years",
    Weight: "14 kg",
    ImageURL: "https://example.com/images/coyote.jpg",
  },
  {
    Animal: "Gray Wolf",
    Diet: "Carnivore",
    Habitat: "Forest",
    Lifespan: "8-13 years",
    Weight: "50 kg",
    ImageURL: "https://example.com/images/gray-wolf.jpg",
  },
  {
    Animal: "Wolverine",
    Diet: "Carnivore",
    Habitat: "Tundra",
    Lifespan: "12-15 years",
    Weight: "18 kg",
    ImageURL: "https://example.com/images/wolverine.jpg",
  },
  {
    Animal: "Badger",
    Diet: "Omnivore",
    Habitat: "Forest",
    Lifespan: "10-15 years",
    Weight: "12 kg",
    ImageURL: "https://example.com/images/badger.jpg",
  },
  {
    Animal: "Marten",
    Diet: "Omnivore",
    Habitat: "Forest",
    Lifespan: "8-10 years",
    Weight: "2 kg",
    ImageURL: "https://example.com/images/marten.jpg",
  },
  {
    Animal: "Fisher",
    Diet: "Carnivore",
    Habitat: "Forest",
    Lifespan: "7-10 years",
    Weight: "6 kg",
    ImageURL: "https://example.com/images/fisher.jpg",
  },
  {
    Animal: "Weasel",
    Diet: "Carnivore",
    Habitat: "Grassland",
    Lifespan: "5-7 years",
    Weight: "0.3 kg",
    ImageURL: "https://example.com/images/weasel.jpg",
  },
  {
    Animal: "Polar Bear",
    Diet: "Carnivore",
    Habitat: "Arctic",
    Lifespan: "20-30 years",
    Weight: "450 kg",
    ImageURL: "https://example.com/images/polar-bear.jpg",
  },
  {
    Animal: "Arctic Fox",
    Diet: "Omnivore",
    Habitat: "Arctic",
    Lifespan: "10-15 years",
    Weight: "9 kg",
    ImageURL: "https://example.com/images/arctic-fox.jpg",
  },
  {
    Animal: "Red Fox",
    Diet: "Omnivore",
    Habitat: "Forest",
    Lifespan: "8-12 years",
    Weight: "7 kg",
    ImageURL: "https://example.com/images/red-fox.jpg",
  },
  {
    Animal: "Snow Leopard",
    Diet: "Carnivore",
    Habitat: "Mountains",
    Lifespan: "15-18 years",
    Weight: "55 kg",
    ImageURL: "https://example.com/images/snow-leopard.jpg",
  },
  {
    Animal: "Cougar",
    Diet: "Carnivore",
    Habitat: "Mountains",
    Lifespan: "8-13 years",
    Weight: "80 kg",
    ImageURL: "https://example.com/images/cougar.jpg",
  },
  {
    Animal: "Lynx",
    Diet: "Carnivore",
    Habitat: "Forest",
    Lifespan: "10-15 years",
    Weight: "25 kg",
    ImageURL: "https://example.com/images/lynx.jpg",
  },
  {
    Animal: "Bobcat",
    Diet: "Carnivore",
    Habitat: "Forest",
    Lifespan: "10-12 years",
    Weight: "14 kg",
    ImageURL: "https://example.com/images/bobcat.jpg",
  },
  {
    Animal: "Jaguar",
    Diet: "Carnivore",
    Habitat: "Rainforest",
    Lifespan: "12-15 years",
    Weight: "100 kg",
    ImageURL: "https://example.com/images/jaguar.jpg",
  },
  {
    Animal: "Panther",
    Diet: "Carnivore",
    Habitat: "Forest",
    Lifespan: "12-17 years",
    Weight: "90 kg",
    ImageURL: "https://example.com/images/panther.jpg",
  },
  {
    Animal: "Ocelot",
    Diet: "Carnivore",
    Habitat: "Rainforest",
    Lifespan: "15-20 years",
    Weight: "15 kg",
    ImageURL: "https://example.com/images/ocelot.jpg",
  },
  {
    Animal: "Serval",
    Diet: "Carnivore",
    Habitat: "Grassland",
    Lifespan: "12-20 years",
    Weight: "18 kg",
    ImageURL: "https://example.com/images/serval.jpg",
  },
  {
    Animal: "Caracal",
    Diet: "Carnivore",
    Habitat: "Savanna",
    Lifespan: "12-15 years",
    Weight: "20 kg",
    ImageURL: "https://example.com/images/caracal.jpg",
  },
  {
    Animal: "Golden Jackal",
    Diet: "Omnivore",
    Habitat: "Grassland",
    Lifespan: "8-12 years",
    Weight: "15 kg",
    ImageURL: "https://example.com/images/golden-jackal.jpg",
  },
  {
    Animal: "African Wild Dog",
    Diet: "Carnivore",
    Habitat: "Savanna",
    Lifespan: "10-12 years",
    Weight: "30 kg",
    ImageURL: "https://example.com/images/african-wild-dog.jpg",
  },
  {
    Animal: "Dingo",
    Diet: "Carnivore",
    Habitat: "Desert",
    Lifespan: "10-13 years",
    Weight: "20 kg",
    ImageURL: "https://example.com/images/dingo.jpg",
  },
  {
    Animal: "Coyote",
    Diet: "Omnivore",
    Habitat: "Grassland",
    Lifespan: "10-14 years",
    Weight: "14 kg",
    ImageURL: "https://example.com/images/coyote.jpg",
  },
  {
    Animal: "Gray Wolf",
    Diet: "Carnivore",
    Habitat: "Forest",
    Lifespan: "8-13 years",
    Weight: "50 kg",
    ImageURL: "https://example.com/images/gray-wolf.jpg",
  },
  {
    Animal: "Wolverine",
    Diet: "Carnivore",
    Habitat: "Tundra",
    Lifespan: "12-15 years",
    Weight: "18 kg",
    ImageURL: "https://example.com/images/wolverine.jpg",
  },
  {
    Animal: "Badger",
    Diet: "Omnivore",
    Habitat: "Forest",
    Lifespan: "10-15 years",
    Weight: "12 kg",
    ImageURL: "https://example.com/images/badger.jpg",
  },
  {
    Animal: "Marten",
    Diet: "Omnivore",
    Habitat: "Forest",
    Lifespan: "8-10 years",
    Weight: "2 kg",
    ImageURL: "https://example.com/images/marten.jpg",
  },
  {
    Animal: "Fisher",
    Diet: "Carnivore",
    Habitat: "Forest",
    Lifespan: "7-10 years",
    Weight: "6 kg",
    ImageURL: "https://example.com/images/fisher.jpg",
  },
  {
    Animal: "Weasel",
    Diet: "Carnivore",
    Habitat: "Grassland",
    Lifespan: "5-7 years",
    Weight: "0.3 kg",
    ImageURL: "https://example.com/images/weasel.jpg",
  },
  {
    Animal: "Otter",
    Diet: "Carnivore",
    Habitat: "River",
    Lifespan: "10-15 years",
    Weight: "14 kg",
    ImageURL: "https://example.com/images/otter.jpg",
  },
  {
    Animal: "Sea Otter",
    Diet: "Carnivore",
    Habitat: "Ocean",
    Lifespan: "15-20 years",
    Weight: "30 kg",
    ImageURL: "https://example.com/images/sea-otter.jpg",
  },
  {
    Animal: "Walrus",
    Diet: "Carnivore",
    Habitat: "Arctic Ocean",
    Lifespan: "30-40 years",
    Weight: "1200 kg",
    ImageURL: "https://example.com/images/walrus.jpg",
  },
  {
    Animal: "Seal",
    Diet: "Carnivore",
    Habitat: "Ocean",
    Lifespan: "25-30 years",
    Weight: "300 kg",
    ImageURL: "https://example.com/images/seal.jpg",
  },
  {
    Animal: "Sea Lion",
    Diet: "Carnivore",
    Habitat: "Ocean",
    Lifespan: "20-30 years",
    Weight: "350 kg",
    ImageURL: "https://example.com/images/sea-lion.jpg",
  },
  {
    Animal: "Dolphin",
    Diet: "Carnivore",
    Habitat: "Ocean",
    Lifespan: "30-50 years",
    Weight: "260 kg",
    ImageURL: "https://example.com/images/dolphin.jpg",
  },
  {
    Animal: "Orca",
    Diet: "Carnivore",
    Habitat: "Ocean",
    Lifespan: "50-90 years",
    Weight: "5400 kg",
    ImageURL: "https://example.com/images/orca.jpg",
  },
  {
    Animal: "Blue Whale",
    Diet: "Carnivore",
    Habitat: "Ocean",
    Lifespan: "80-90 years",
    Weight: "150000 kg",
    ImageURL: "https://example.com/images/blue-whale.jpg",
  },
  {
    Animal: "Humpback Whale",
    Diet: "Carnivore",
    Habitat: "Ocean",
    Lifespan: "45-50 years",
    Weight: "36000 kg",
    ImageURL: "https://example.com/images/humpback-whale.jpg",
  },
  {
    Animal: "Sperm Whale",
    Diet: "Carnivore",
    Habitat: "Ocean",
    Lifespan: "60-70 years",
    Weight: "41000 kg",
    ImageURL: "https://example.com/images/sperm-whale.jpg",
  },
  {
    Animal: "Manatee",
    Diet: "Herbivore",
    Habitat: "Coastal Waters",
    Lifespan: "40-60 years",
    Weight: "500 kg",
    ImageURL: "https://example.com/images/manatee.jpg",
  },
  {
    Animal: "Dugong",
    Diet: "Herbivore",
    Habitat: "Coastal Waters",
    Lifespan: "60-70 years",
    Weight: "420 kg",
    ImageURL: "https://example.com/images/dugong.jpg",
  },
  {
    Animal: "Great White Shark",
    Diet: "Carnivore",
    Habitat: "Ocean",
    Lifespan: "30-40 years",
    Weight: "1100 kg",
    ImageURL: "https://example.com/images/great-white-shark.jpg",
  },
  {
    Animal: "Hammerhead Shark",
    Diet: "Carnivore",
    Habitat: "Ocean",
    Lifespan: "20-30 years",
    Weight: "450 kg",
    ImageURL: "https://example.com/images/hammerhead-shark.jpg",
  },
  {
    Animal: "Tiger Shark",
    Diet: "Carnivore",
    Habitat: "Ocean",
    Lifespan: "25-40 years",
    Weight: "900 kg",
    ImageURL: "https://example.com/images/tiger-shark.jpg",
  },
  {
    Animal: "Manta Ray",
    Diet: "Carnivore",
    Habitat: "Ocean",
    Lifespan: "20-25 years",
    Weight: "1350 kg",
    ImageURL: "https://example.com/images/manta-ray.jpg",
  },
  {
    Animal: "Stingray",
    Diet: "Carnivore",
    Habitat: "Ocean",
    Lifespan: "15-25 years",
    Weight: "350 kg",
    ImageURL: "https://example.com/images/stingray.jpg",
  },
  {
    Animal: "Octopus",
    Diet: "Carnivore",
    Habitat: "Ocean",
    Lifespan: "1-5 years",
    Weight: "15 kg",
    ImageURL: "https://example.com/images/octopus.jpg",
  },
  {
    Animal: "Squid",
    Diet: "Carnivore",
    Habitat: "Ocean",
    Lifespan: "1-3 years",
    Weight: "20 kg",
    ImageURL: "https://example.com/images/squid.jpg",
  },
  {
    Animal: "Jellyfish",
    Diet: "Carnivore",
    Habitat: "Ocean",
    Lifespan: "1-2 years",
    Weight: "0.2 kg",
    ImageURL: "https://example.com/images/jellyfish.jpg",
  },
  {
    Animal: "Sea Turtle",
    Diet: "Omnivore",
    Habitat: "Ocean",
    Lifespan: "50-100 years",
    Weight: "300 kg",
    ImageURL: "https://example.com/images/sea-turtle.jpg",
  },
  {
    Animal: "Penguin",
    Diet: "Carnivore",
    Habitat: "Polar Regions",
    Lifespan: "15-20 years",
    Weight: "30 kg",
    ImageURL: "https://example.com/images/penguin.jpg",
  },
  {
    Animal: "Pelican",
    Diet: "Carnivore",
    Habitat: "Coastal",
    Lifespan: "20-25 years",
    Weight: "10 kg",
    ImageURL: "https://example.com/images/pelican.jpg",
  },
  {
    Animal: "Albatross",
    Diet: "Carnivore",
    Habitat: "Ocean",
    Lifespan: "40-60 years",
    Weight: "9 kg",
    ImageURL: "https://example.com/images/albatross.jpg",
  },
  {
    Animal: "Eagle",
    Diet: "Carnivore",
    Habitat: "Mountains",
    Lifespan: "20-30 years",
    Weight: "6 kg",
    ImageURL: "https://example.com/images/eagle.jpg",
  },
  {
    Animal: "Falcon",
    Diet: "Carnivore",
    Habitat: "Cliffs",
    Lifespan: "12-15 years",
    Weight: "1.5 kg",
    ImageURL: "https://example.com/images/falcon.jpg",
  },
  {
    Animal: "Hawk",
    Diet: "Carnivore",
    Habitat: "Forest",
    Lifespan: "15-20 years",
    Weight: "1.2 kg",
    ImageURL: "https://example.com/images/hawk.jpg",
  },
  {
    Animal: "Owl",
    Diet: "Carnivore",
    Habitat: "Forest",
    Lifespan: "15-25 years",
    Weight: "2 kg",
    ImageURL: "https://example.com/images/owl.jpg",
  },
  {
    Animal: "Vulture",
    Diet: "Carnivore",
    Habitat: "Savanna",
    Lifespan: "30-40 years",
    Weight: "9 kg",
    ImageURL: "https://example.com/images/vulture.jpg",
  },
  {
    Animal: "Crow",
    Diet: "Omnivore",
    Habitat: "Urban",
    Lifespan: "15-20 years",
    Weight: "0.5 kg",
    ImageURL: "https://example.com/images/crow.jpg",
  },
  {
    Animal: "Raven",
    Diet: "Omnivore",
    Habitat: "Mountains",
    Lifespan: "10-15 years",
    Weight: "1.3 kg",
    ImageURL: "https://example.com/images/raven.jpg",
  },
  {
    Animal: "Parrot",
    Diet: "Herbivore",
    Habitat: "Rainforest",
    Lifespan: "50-80 years",
    Weight: "1 kg",
    ImageURL: "https://example.com/images/parrot.jpg",
  },
  {
    Animal: "Macaw",
    Diet: "Herbivore",
    Habitat: "Rainforest",
    Lifespan: "50 years",
    Weight: "1.2 kg",
    ImageURL: "https://example.com/images/macaw.jpg",
  },
  {
    Animal: "Cockatoo",
    Diet: "Herbivore",
    Habitat: "Forest",
    Lifespan: "40-60 years",
    Weight: "0.9 kg",
    ImageURL: "https://example.com/images/cockatoo.jpg",
  },
  {
    Animal: "Pigeon",
    Diet: "Herbivore",
    Habitat: "Urban",
    Lifespan: "5-15 years",
    Weight: "0.3 kg",
    ImageURL: "https://example.com/images/pigeon.jpg",
  },
  {
    Animal: "Sparrow",
    Diet: "Omnivore",
    Habitat: "Urban",
    Lifespan: "3-5 years",
    Weight: "0.02 kg",
    ImageURL: "https://example.com/images/sparrow.jpg",
  },
  {
    Animal: "Peacock",
    Diet: "Omnivore",
    Habitat: "Forest",
    Lifespan: "15-20 years",
    Weight: "6 kg",
    ImageURL: "https://example.com/images/peacock.jpg",
  },
  {
    Animal: "Flamingo",
    Diet: "Omnivore",
    Habitat: "Wetlands",
    Lifespan: "20-30 years",
    Weight: "3 kg",
    ImageURL: "https://example.com/images/flamingo.jpg",
  },
  {
    Animal: "Swan",
    Diet: "Herbivore",
    Habitat: "Lakes",
    Lifespan: "20-30 years",
    Weight: "14 kg",
    ImageURL: "https://example.com/images/swan.jpg",
  },
  {
    Animal: "Duck",
    Diet: "Omnivore",
    Habitat: "Wetlands",
    Lifespan: "5-10 years",
    Weight: "1.5 kg",
    ImageURL: "https://example.com/images/duck.jpg",
  },
  {
    Animal: "Goose",
    Diet: "Herbivore",
    Habitat: "Wetlands",
    Lifespan: "10-25 years",
    Weight: "5 kg",
    ImageURL: "https://example.com/images/goose.jpg",
  },
  {
    Animal: "Turkey",
    Diet: "Omnivore",
    Habitat: "Forest",
    Lifespan: "10 years",
    Weight: "11 kg",
    ImageURL: "https://example.com/images/turkey.jpg",
  },
  {
    Animal: "Ostrich",
    Diet: "Omnivore",
    Habitat: "Savanna",
    Lifespan: "40-45 years",
    Weight: "140 kg",
    ImageURL: "https://example.com/images/ostrich.jpg",
  },
  {
    Animal: "Emu",
    Diet: "Omnivore",
    Habitat: "Grassland",
    Lifespan: "10-20 years",
    Weight: "45 kg",
    ImageURL: "https://example.com/images/emu.jpg",
  },
  {
    Animal: "Cassowary",
    Diet: "Omnivore",
    Habitat: "Rainforest",
    Lifespan: "40-50 years",
    Weight: "60 kg",
    ImageURL: "https://example.com/images/cassowary.jpg",
  },
  {
    Animal: "Kiwi",
    Diet: "Omnivore",
    Habitat: "Forest",
    Lifespan: "25-50 years",
    Weight: "2.5 kg",
    ImageURL: "https://example.com/images/kiwi.jpg",
  },
  {
    Animal: "Woodpecker",
    Diet: "Insectivore",
    Habitat: "Forest",
    Lifespan: "7-12 years",
    Weight: "0.3 kg",
    ImageURL: "https://example.com/images/woodpecker.jpg",
  },
  {
    Animal: "Kingfisher",
    Diet: "Carnivore",
    Habitat: "Rivers",
    Lifespan: "6-10 years",
    Weight: "0.04 kg",
    ImageURL: "https://example.com/images/kingfisher.jpg",
  },
  {
    Animal: "Hornbill",
    Diet: "Omnivore",
    Habitat: "Forest",
    Lifespan: "35-40 years",
    Weight: "4 kg",
    ImageURL: "https://example.com/images/hornbill.jpg",
  },
  {
    Animal: "Toucan",
    Diet: "Herbivore",
    Habitat: "Rainforest",
    Lifespan: "20-25 years",
    Weight: "0.7 kg",
    ImageURL: "https://example.com/images/toucan.jpg",
  },
  {
    Animal: "Hummingbird",
    Diet: "Herbivore",
    Habitat: "Forest",
    Lifespan: "3-5 years",
    Weight: "0.004 kg",
    ImageURL: "https://example.com/images/hummingbird.jpg",
  },
  {
    Animal: "Bat",
    Diet: "Omnivore",
    Habitat: "Caves",
    Lifespan: "10-30 years",
    Weight: "0.03 kg",
    ImageURL: "https://example.com/images/bat.jpg",
  },
  {
    Animal: "Flying Fox",
    Diet: "Herbivore",
    Habitat: "Forest",
    Lifespan: "15-20 years",
    Weight: "1 kg",
    ImageURL: "https://example.com/images/flying-fox.jpg",
  },
];

function page() {
  // Pass Animals array as prop
  return (
    <div>
      <RandomAnimalGen animals={Animals} />
    </div>
  );
}

export default page;
